services:
- type: web
  name: todo-api
  runtime: ruby
  repo: https://github.com/iamcaiorian/todo-api
  plan: starter
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: RAILS_MASTER_KEY
    sync: false
  - key: WEB_CONCURRENCY
    sync: false
  region: oregon
  buildCommand: bundle install; bundle exec rake assets:precompile; bundle exec rake
    assets:clean; ./bin/render-build.sh;
  startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}
    ./bin/rails server
version: "1"
