default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: <%= ENV['TODO_API_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: todo_api_development

test:
  <<: *default
  database: todo_api_test

production:
  <<: *default
  database: todo_api_production
  username: todo_api
  password: <%= ENV['TODO_API_DATABASE_PASSWORD'] %>